//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COMPANYFEATURETAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANYFEATURETAB()
        {
            this.COMPANies = new HashSet<COMPANY>();
        }

        [Required]
        public string CompanyFeatureTabID { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "【此標籤最多10個字】我們知道膩的公司很有特色，但是請長話短說！")]
        public string CompanyFeature { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY> COMPANies { get; set; }
    }
}
