//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class COMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANY()
        {
            this.EMPLOYERs = new HashSet<EMPLOYER>();
            this.COMPANYFEATURETABs = new HashSet<COMPANYFEATURETAB>();
        }
        [Key]
        [Required]
        public string CompanyID { get; set; }

        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "電話號碼格式不正確。(請勿輸入「-」或是空格，正確範例：0912345678。)")]
        [RegularExpression("([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]*)", ErrorMessage = "電話號碼格式不正確。(請勿輸入「-」或是空格，正確範例：0912345678。)")]
        public string Tel { get; set; }

        [Required]
        [StringLength(300, ErrorMessage = "請勿輸入過長的文字敘述")]
        public string Address { get; set; }

        [Required]
        [StringLength(30)]
        public string Industry { get; set; }

        [AllowHtml]
        public string Intro { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYER> EMPLOYERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANYFEATURETAB> COMPANYFEATURETABs { get; set; }
    }
}
