//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EVENT_WORKER_JUNCTION
    {
        [Key, Column(Order = 1)]
        public string EventID { get; set; }

        [Key, Column(Order = 1)]
        public string WorkerID { get; set; }
        public bool Hire { get; set; }
        public bool Finished { get; set; }
        public Nullable<System.DateTime> HireDateTime { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual WORKER WORKER { get; set; }
    }
}
