//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.EVENT_WORKER_JUNCTION = new HashSet<EVENT_WORKER_JUNCTION>();
            this.EVENTTABs = new HashSet<EVENTTAB>();
            this.SKILLTABs = new HashSet<SKILLTAB>();
            this.WORKERs = new HashSet<WORKER>();
            this.REQUIREDSKILLTABs = new HashSet<REQUIREDSKILLTAB>();
        }

        [Required]
        public string EventID { get; set; }

        [Required]
        [StringLength(300, ErrorMessage = "300個字元已經夠長了，剩下的擺底下的敘述。")]
        public string Name { get; set; }

        [Required]
        //[CheckValidDate]
        //[DisplayFormat(DataFormatString = "{yyyy/M/d}")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/M/d}")]
        public System.DateTime Date { get; set; }

        [Required]
        //[DataType(DataType.Time)]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan Time_Start { get; set; }

        //[DataType(DataType.Time)]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> Time_End { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "電話號碼格式不正確。(請勿輸入「-」或是空格，正確範例：0912345678。)")]
        [RegularExpression("([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]*)", ErrorMessage = "電話號碼格式不正確。(請勿輸入「-」或是空格，正確範例：0912345678。)")]
        public string Tel { get; set; }

        [Required]
        [StringLength(300, ErrorMessage = "請勿輸入過長的文字敘述")]
        public string Address { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "應徵人不應低於0")]
        public int NumberOfWorkers { get; set; }

        [Required]
        public string EmployerID { get; set; }

        [Range(160, int.MaxValue, ErrorMessage = "最低時薪160NT$/hr。")]
        public Nullable<int> Wage_byHour { get; set; }

        [StringLength(300, ErrorMessage = "請勿輸入過長的文字敘述。")]
        public string Wage_byOthers { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "履歷上限不應低於應徵人數")]
        public Nullable<int> maxResumeNumber { get; set; }

        [AllowHtml]
        public string Abouts { get; set; }

        //[CheckValidDate]
        [Required(ErrorMessage = "請輸入同時符合晚於當下時刻且早於工作日期的時間")]
        //[DisplayFormat(DataFormatString = "{yyyy/M/d hh:mm}")]
        [DisplayFormat(DataFormatString = "{yyyy/M/d hh:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime OffListTime { get; set; }
        public bool Finished { get; set; }
        public bool I { get; set; }
        public bool E { get; set; }
        public bool N { get; set; }
        public bool S { get; set; }
        public bool T { get; set; }
        public bool F { get; set; }
        public bool P { get; set; }
        public bool J { get; set; }
        public string RequiredCharacter { get; set; }

        [Required]
        public int LackofWorkers { get; set; }
    
        public virtual EMPLOYER EMPLOYER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT_WORKER_JUNCTION> EVENT_WORKER_JUNCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTTAB> EVENTTABs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKILLTAB> SKILLTABs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKER> WORKERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUIREDSKILLTAB> REQUIREDSKILLTABs { get; set; }
    }
}
