//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finalprojectEntities : DbContext
    {
        public finalprojectEntities()
            : base("name=finalprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<COMPANY> Companies { get; set; }
        public virtual DbSet<COMPANYFEATURETAB> CompanyFeatureTabs { get; set; }
        public virtual DbSet<EMPLOYER> Employers { get; set; }
        public virtual DbSet<EVENT> Events { get; set; }
        public virtual DbSet<EVENTTAB> EventTabs { get; set; }
        public virtual DbSet<SKILLTAB> SkillTabs { get; set; }
        public virtual DbSet<EVENT_WORKER_JUNCTION> Hires { get; set; }
        public virtual DbSet<WORKER> Workers { get; set; }
        public virtual DbSet<REQUIREDSKILLTAB> RequiredSkillTabs { get; set; }
    }
}
